import type { NextPage } from 'next'
import Head from 'next/head'
import HeroSection from '../components/HeroSection'
import Navbar from '../components/Navbar'

const Home: NextPage = () => {
  return (
    <div >
      <Head>
        <title>Agustín</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='fixed top-0 w-full z-0 md:h-28 lg:h-36 h-24 border-black dark:border-white border-b-2'>
      </div>
      <Navbar />
      <main>
        <HeroSection />
      </main>
    </div>
  )
}

export default Home;
