import type { NextPage } from 'next'
import Head from 'next/head'
import HeroSection from '../components/HeroSection'
import Navbar from '../components/Navbar'
import SocialIcons from '../components/SocialIcons'

const Home: NextPage = () => {
  return (
    <div >
      <Head>
        <title>Agustín</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main>
        <HeroSection />
        <SocialIcons />
      </main>
    </div>
  )
}

export default Home;
